### ISSUE TITLE
Ubuntu update.sh

### ISSUE THREAD

**Issue by jsenon** [jriguera/packer-ironic-images#2]
Hello,
update script and more precisely apt-get -y dist-upgrade cause crash during generation of image

**Comment by jriguera** [comment]
@jsenon I am not able to reproduce the issue, but I think it is because you are using a proxy. Could you give a try again with the new templates and with the instructions I wrote in the [Readme](https://github.com/jriguera/packer-ironic-images/blob/master/ubuntu/README.md#proxy)?

**Comment by jsenon** [comment]
@jriguera I will test it. Thanks for the update

**Comment by jsenon** [comment]
@jriguera that's works. Thx
